# Generated by Django 4.2.16 on 2025-07-10 17:58

from django.db import migrations, models
import portal.models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchpaper',
            name='document',
            field=models.FileField(upload_to=portal.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='researchpaper',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', max_length=20),
        ),
    ]
